routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
Route::get('/',function (){
   return view('auth.login');
});
Route::group(['middleware' => 'auth'], function (){
    Route::post('/logout','AuthController@logout')->name('auth.logout');
    Route::get('/nouvel-utilisateur', function (){
        return view('pages.auth.register');
    });
    Route::post('/register','AuthController@store')->name('auth.store');

    Route::group(['prefix' => 'dashboard'], function (){
        Route::get('/','HomeController@index')->name('home');

        // militaires routes

        Route::get('/militaires','MilitaireController@index')->name('militaire.home');
        Route::get('/militaire/{id}','MilitaireController@show')->name('militaire.show');
        Route::get('/militaire/delete/{id}','MilitaireController@destroy_partial')->name('militaire.delete');
        Route::get('/militaire/{id}/informations','MilitaireController@details')->name('militaire.fiche');
        Route::post('/militaires','MilitaireController@storeOrUpdate')->name('militaire.store');
        Route::post('/militaire-grade','MilitaireGradeController@store')->name('militaire.store_grade');
        Route::post('/militaire/edit-photo','MilitaireController@update_photo')->name('militaire.photo');

        // grades routes

        Route::get('/grades-militaires', 'GradeController@index')->name('grade.home');
        Route::get('/grades-militaires/{id}','GradeController@show')->name('grade.show');
        Route::get('/grades-militaires/{id}/delete','GradeController@destroy')->name('grade.delete');
        Route::post('/grades-militaires', 'GradeController@store')->name('grade.store');

        // Type Logement routes

        Route::get('/type-de-logemets','TypeLogementController@index')->name('typeL.home');
        Route::get('/type-de-logemets/{id}','TypeLogementController@show')->name('typeL.show');
        Route::get('/type-de-logemets/{id}/delete','TypeLogementController@destroy')->name('typeL.delete');
        Route::post('/type-de-logemets','TypeLogementController@store')->name('typeL.store');

        // Emplacement routes
        Route::get('/emplacements','EmplacementController@index')->name('emplacement.home');
        Route::post('/emplacements','EmplacementController@store')->name('emplacement.store');
        Route::get('/emplacements/{id}','EmplacementController@show')->name('emplacement.show');
        Route::get('/emplacements/{id}/delete','EmplacementController@destroy')->name('emplacement.delete');

        // Logements Routes
        Route::get('/logements','LogementController@index')->name('logement.home');
        Route::post('/logements','LogementController@store')->name('logement.store');
        Route::get('/logements/{id}','LogementController@show')->name('logement.edit');
        Route::get('/logements/{id}/delete','LogementController@destroy')->name('logement.delete');
        Route::get('/logement/{id}/informations','LogementController@informations')->name('logement.infos');

        // Anciens Logements routes

        Route::get('/anciens_logements','AncienLogementController@index')->name('ancienL.home');
        Route::get('/anciens_logements/{id}','AncienLogementController@show');
        Route::get('/anciens_logements/{id}/delete','AncienLogementController@destroy');
        Route::post('/anciens_logements','AncienLogementController@store')->name('ancienL.store');

        // Propriétaires Routes
        Route::get('/proprietaires','PropietaireController@index')->name('proprio.home');
        Route::post('/proprietaires','PropietaireController@store')->name('proprio.store');
        Route::get('/proprietaires/{id}','PropietaireController@show')->name('proprio.show');
        Route::get('/proprietaires/{id}/delete','PropietaireController@destroy')->name('proprio.delete');
        Route::get('/proprietaires/{id}/informations', 'PropietaireController@infos');

        // Compte routes

        Route::get('/comptes', 'CompteController@index')->name('compte.home');
        Route::get('/comptes/{id}', 'CompteController@show')->name('compte.edit');
        Route::get('/comptes/{id}/delete', 'CompteController@destroy')->name('compte.delete');
        Route::get('/comptes/{id}/informations', 'CompteController@infos')->name('compte.show');
        Route::post('/comptes', 'CompteController@store')->name('compte.store');

        // USER MANAGEMENT ROUTES

        Route::get('/utilisateurs', 'UserController@index')->name('user.home');
        Route::post('/utilisateurs', 'UserController@store')->name('user.store');
        Route::get('/utilisateurs/{id}', 'UserController@show')->name('user.show');
        Route::get('/utilisateurs/{id}/delete', 'UserController@destroy')->name('user.show');

        // ROLE ROUTES

        Route::resource('habilitations','RoleController');
    });
});

Auth::routes(['register' => false]);

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/inc/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>2020 - Copyright &copy; Base Aérienne d'Abidjan | Tous droits réservés</span><br><br>
            <span><b>Designed by <a href="mailto:ernestkouassi02@gmail.com" target="_blank">Ernest K.</a></b></span>
        </div>
    </div>
</footer>

resources/views/inc/sideBar.blade.php
<ul class="navbar-nav bg-gradient-light sidebar sidebar-light accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('home')}}">
        <div class="sidebar-brand-icon rotate-n-15">
           <img src="{{asset('assets/img/logo.png')}}" class="img-fluid img-profile" width="50">
        </div>
        <div class="sidebar-brand-text mx-3">Baux Miliatires</div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item @yield('home-active')">
        <a class="nav-link" href="{{route('home')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Accueil</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Pages
    </div>
    <li class="nav-item @yield('militaire-active')">
        <a class="nav-link" href="/dashboard/militaires">
            <i class="fas fa-fw fa-user-shield"></i>
            <span>Militaires</span></a>
    </li>
    <li class="nav-item @yield('grade-active')">
        <a class="nav-link" href="/dashboard/grades-militaires">
            <i class="fas fa-fw fa-user-graduate"></i>
        <span>Grades</span></a>
    </li>
    <li class="nav-item @yield('logement-active')">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-house-damage"></i>
            <span>Logements</span>
        </a>
        <div id="collapseTwo" class="collapse @yield('logement-show')" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item @yield('type_l-active')" href="/dashboard/type-de-logemets">Type De Logements</a>
                <a class="collapse-item @yield('l_actuel-active')" href="{{route('logement.home')}}">Logements Actuels</a>
                <a class="collapse-item @yield('l_ancien-active')" href="{{route('ancienL.home')}}">Anciens Logements</a>
            </div>
        </div>
    </li>
    <li class="nav-item @yield('proprietaire-active')">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Propriétaires</span>
        </a>
        <div id="collapseUtilities" class="collapse @yield('proprietaire-show')" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item @yield('active_pListe')" href="{{route('proprio.home')}}">Liste Propriétaires</a>
                <a class="collapse-item @yield('active_compte')" href="{{route('compte.home')}}">Comptes Propriétaires</a>
            </div>
        </div>
    </li>
    <li class="nav-item @yield('emplacement-active')">
        <a class="nav-link" href="/dashboard/emplacements">
            <i class="fas fa-fw fa-map-marker"></i>
            <span>Emplacements</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Administration
    </div>
    <li class="nav-item @yield('users-active')">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-users-cog"></i>
            <span>Utilisateurs Mangement</span>
        </a>
        <div id="collapsePages" class="collapse @yield('users-show')" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item @yield('user')" href="{{route('user.home')}}">Utilsateurs</a>
                <a class="collapse-item @yield('role')" href="{{route('habilitations.index')}}">Niveau Habilétés</a>
            </div>
        </div>
    </li>
    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

resources/views/inc/topBar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" action="#" method="POST">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Taper la recherche..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search" action="#" method="POST">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Taper la recherche..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger badge-counter">1</span>
            </a>
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Centre d'alertes
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">04, Septembre 2020</div>
                        <span class="font-weight-bold">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Voir toutes les alertes</a>
            </div>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{Auth::user()->firstName.' '.Auth::user()->lastName}}</span>
                <img class="img-profile rounded-circle" src="{{Auth::user()->avatar}}">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profil
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Paramètres
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Déconnexion
                </a>
            </div>
        </li>

    </ul>

</nav>